name: Deploy Todo App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '12.x'
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli@9.0.1
      
      - name: Install and build
        run: |
          npm ci
          ng build --prod --base-href "/todo/"
      
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/your-project-name  # Adjust to your output path
          # destination_dir: todo  # Creates /todo subdirectory in gh-pages
          keep_files: false  # Cleans previous deployment
